name: saman_carriers_task
description: First Task For Developers

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_switch: ^0.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:

    - family: Jameel Noori Nastaleeq
      fonts:
        - asset: assets/fonts/JameelNooriNastaleeqRegular.ttf